[site]
title="Yarnom'Blog"
language="en"

[menu]
[[menu_item]]
title="归档"
link="/archive"

[[menu_item]]
title="标签"
link="/archive/tags"

[[menu_item]]
title="分类 "
link="/archive/categories"

[[menu_item]]
title="友链"
link="/link"

[[menu_item]]
title="关于"
link="/about"
